"""Curated source data for the open-humanoid catalog and the builder.

Hand-maintained. tools/build_catalog.py merges this with the computed modules of
the Fully Open Humanoid (from robot.json / bom.json) and of Duke Humanoid V2
(from the CSVs in Duke_Humanoid_V2_OpenSource/hardware-site/docs/data) and
writes assets/data/catalog.json.

Every robot carries the URLs its facts were read from (sources). Openness
values: "yes" | "partial" | "no" | "unknown". Prices are what the project or a
named third party published; price_basis says which. Nothing here is a
measurement of ours except the Fully Open Humanoid itself, which is a design
that has not been built.
"""

CRITERIA = [
    dict(id="cad", name="Editable CAD", short="CAD",
         desc="Design source in a form you could change: native parametric files or a public Onshape document. STL or STEP exports alone count as partial."),
    dict(id="bom", name="Itemised BOM", short="BOM",
         desc="Every purchased part with quantity, price and a vendor or part number."),
    dict(id="docs", name="Build documentation", short="Docs",
         desc="Assembly instructions or a build guide a third party could follow: print settings, order of assembly, wiring."),
    dict(id="elec", name="Electronics source", short="Elec",
         desc="Schematics and PCB files for any custom board, or every board is an off-the-shelf part."),
    dict(id="fw", name="Firmware and low-level code", short="Code",
         desc="The code that talks to the actuators and runs the control loop on the robot."),
    dict(id="sim", name="Robot description and simulation", short="Sim",
         desc="URDF, MJCF or USD with masses and limits, and a simulation setup that uses it."),
    dict(id="policy", name="Working controller", short="Ctrl",
         desc="A released controller or trained policy that makes the released hardware stand and walk (or, for arms and hands, move usefully)."),
    dict(id="lic", name="Open hardware licence", short="Lic",
         desc="A stated hardware licence that permits study, modification, manufacture and sale (OSHWA definition): CERN-OHL, CC BY, CC BY-SA, MIT, Apache, BSD, Solderpad. Non-commercial terms or no licence fail."),
    dict(id="built", name="Reproduced", short="Built",
         desc="Built by the authors and reproduced by someone else, or sold as a kit; the release has been shown to be buildable."),
]

SLOTS = [
    dict(id="lower", name="Lower body", desc="Pelvis, hips, legs and feet, with their actuators."),
    dict(id="torso", name="Torso", desc="Waist joint, frame, computer, power and IMU."),
    dict(id="arms", name="Arms", desc="Shoulders to wrists, both sides."),
    dict(id="hands", name="Hands", desc="Grippers or hands, both sides."),
    dict(id="head", name="Head", desc="Head structure and perception."),
]

# Actuator families the compatibility checks compare.
FAMILIES = {
    "robstride-rs": dict(name="RobStride RS-series", bus="CAN 2.0, 1 Mbit/s", protocol="RobStride private CAN protocol, MIT-mode PD", voltage_v=48),
    "robstride-o": dict(name="RobStride O-series", bus="CAN-FD", protocol="RobStride CAN-FD protocol", voltage_v=48),
    "bhl": dict(name="Berkeley Humanoid Lite printed actuator", bus="CAN (custom controller board)", protocol="BHL motor-controller firmware", voltage_v=None),
    "dynamixel-x": dict(name="Dynamixel X-series", bus="TTL / RS-485 daisy chain", protocol="Dynamixel Protocol 2.0", voltage_v=12),
    "dynamixel-q": dict(name="Dynamixel Q-series", bus="RS-485 / EtherCAT (per ROBOTIS)", protocol="Dynamixel Protocol 2.0", voltage_v=48),
    "feetech-sts": dict(name="Feetech STS bus servo", bus="TTL half-duplex serial", protocol="Feetech SCS/STS protocol", voltage_v=12),
    "cubemars-ak": dict(name="CubeMars AK-series", bus="CAN 2.0", protocol="CubeMars MIT-mode", voltage_v=48),
    "odri": dict(name="ODRI brushless module", bus="SPI to master board, Ethernet to PC", protocol="ODRI master-board protocol", voltage_v=24),
    "damiao": dict(name="Damiao DM-J series", bus="CAN 2.0", protocol="Damiao MIT-mode", voltage_v=48),
    "hobby-pwm": dict(name="Hobby PWM servo", bus="PWM", protocol="PWM pulse width", voltage_v=6),
    "bear": dict(name="Westwood BEAR", bus="RS-485", protocol="BEAR protocol", voltage_v=None),
    "none": dict(name="No actuators", bus="", protocol="", voltage_v=None),
}

# --- robots -------------------------------------------------------------------
# type: full | biped | upper | mini | hand | arm
# status: design | prototype | walking | commercial | archive | announced

ROBOTS = [
    dict(checked="2026-09-25", id="foh", name="Fully Open Humanoid v0.2", org="This site", year=2026, type="full", status="design",
         height_mm=1114, mass_kg=27.8, dof=23, actuators="RobStride RS03 ×11, RS06 ×6, RS02 ×4, RS05 ×2", family="robstride-rs",
         structure="FDM-printed PETG-CF and PLA, four 2020 extrusions", compute="Intel N100 mini PC",
         price_usd=5824, price_basis="itemised", price_note="Core BOM, priced 2026-09; unbuilt design.",
         license_hw="MIT (data and tools), CC BY 4.0 (docs)", license_sw="MIT",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="partial", sim="yes", policy="no", lic="yes", built="no"),
         open_notes=dict(cad="Generated from tools/build_data.py; every printed part as STL with features. Not a conventional CAD document.",
                         fw="Plan only: reuses Duke V2's deploy code and BHL's policy runner; not written.",
                         policy="Stands and crouches under stiff PD in MuJoCo; no walking policy yet.",
                         built="Nothing printed or assembled. v0.3 is the first joint-kit test."),
         links=dict(site="https://fullyopenhml.github.io/", repo="https://github.com/fullyopenhml/fullyopenhml.github.io", bom="https://fullyopenhml.github.io/bom.html", cad="https://fullyopenhml.github.io/printing.html"),
         sources=["https://fullyopenhml.github.io/design.html"],
         summary="Duke Humanoid V2's joint layout on RobStride actuators with every structural part printed, in the spirit of Berkeley Humanoid Lite. A design release: BOM, printable parts, URDF and a MuJoCo standing check exist; nothing has been built.",
         verdict="Open by construction, unproven by construction. Treat every number as a design estimate until the joint-kit test."),

    dict(checked="2026-09-25", id="bhl", name="Berkeley Humanoid Lite", org="UC Berkeley, Hybrid Robotics", year=2025, type="full", status="walking",
         height_mm=800, mass_kg=16, dof=22, actuators="22 printed cycloidal actuators (BLDC motor + custom controller board); the paper abstract states only the sub-$5,000 cost", family="bhl",
         structure="FDM-printed PLA/PETG structure and gearboxes; off-the-shelf metal parts", compute="Onboard computer + microcontroller motor boards",
         price_usd=5000, price_basis="published-total", price_note="\"Sub-$5,000\" per the project; itemised Google Sheet BOM linked from the docs.",
         license_hw="CC BY-SA 4.0 (repository README); MakerWorld files CC BY; the assets repository's LICENCE file", license_sw="MIT",
         open=dict(cad="yes", bom="yes", docs="yes", elec="partial", fw="yes", sim="yes", policy="yes", lic="yes", built="partial"),
         open_notes=dict(cad="Public Onshape document; anonymous export allowed. MakerWorld 3MF print plates.",
                         elec="Motor controller firmware is released; the board's design files were not found in the repository.",
                         policy="Trained checkpoints ship in the repository; zero-shot sim-to-real walking shown in the paper.",
                         built="Built and walking at Berkeley; third-party builds are reported informally, no kit."),
         links=dict(site="https://lite.berkeley-humanoid.org/", repo="https://github.com/HybridRobotics/Berkeley-Humanoid-Lite", docs="https://berkeley-humanoid-lite.gitbook.io/docs", paper="https://arxiv.org/abs/2504.17249", bom="https://berkeley-humanoid-lite.gitbook.io/docs/getting-started-with-hardware/materials-and-parts-bom"),
         sources=["https://berkeley-humanoid-lite.gitbook.io/docs", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://arxiv.org/abs/2504.17249"],
         summary="The reference for a desktop-printable full-body humanoid: 22 DOF, printed cycloidal gearboxes, everything on hobby-grade tooling, documented failure modes.",
         verdict="Meets the open-hardware definition and is reproducible on a desktop printer. The first project to study for a low-cost full-body build."),

    dict(checked="2026-09-25", id="duke2", name="Duke Humanoid V2", org="Duke University, General Robotics Lab", year=2026, type="full", status="walking",
         height_mm=1256, mass_kg=35.3, dof=31, actuators="RobStride RS00 ×2, RS02 ×6, RS03 ×11, RS04 ×2, RS05 ×6, RS06 ×4; 2 Feetech gripper servos", family="robstride-rs",
         structure="Machined aluminium 6061; PLA, TPU and SLS nylon-12 prints", compute="MINISFORUM X1-470 mini PC",
         price_usd=14882, price_basis="itemised", price_note="Team BOM grand total $14,882 (CNC parts $6,390). The curated CSVs on the project's hardware site total about $13,000 without consumables.",
         license_hw="Apache-2.0 (public repository licence, checked 2026-09-25; the docs' licence page says the same for CAD, drawings and BOM)", license_sw="Apache-2.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="partial", lic="yes", built="yes"),
         open_notes=dict(cad="Fusion 360 source, per-part STEP, module tree and drawings.",
                         elec="All boards off the shelf: CANable adapters, buck converters, TVS diodes.",
                         policy="Deploy code and Isaac Lab training are released; a public walking checkpoint for V2 was not confirmed.",
                         lic="The public repository is Apache-2.0 and the documentation applies it to CAD, drawings and BOM. An internal hand-off note in the working copy still calls the decision pending, so confirm the LICENSE file shipped with the CAD release.",
                         built="Built and walking at Duke (V2 paper, 2026). V1 (2024) was MIT-licensed."),
         links=dict(site="https://generalroboticslab.github.io/Duke_Humanoid_V2_OpenSource/", repo="https://github.com/generalroboticslab/duke_humanoid_v2"),
         sources=["Duke_Humanoid_V2_OpenSource/hardware-site/docs/reference/full-specifications.md", "Duke_Humanoid_V2_OpenSource/hardware-site/docs/reference/citation-and-license.md", "Duke_Humanoid_V2_OpenSource/reference/bom/duke-humanoid-v2_BOM_sheet1_main.csv"],
         summary="A 1.26 m, 31-joint RobStride humanoid with two gimballed depth cameras, machined aluminium legs and a fully priced BOM. The design this site's own robot derives from.",
         verdict="Complete release with real build data under Apache-2.0. The machined parts are the cost and the sourcing burden."),

    dict(checked="2026-09-25", id="roboto", name="Roboto Origin", org="RoboParty (Shanghai)", year=2025, type="full", status="walking",
         height_mm=1250, mass_kg=34, dof=23, actuators="21 servo actuators, 120 N·m legs and 27 N·m arms; models not confirmed", family="unknown",
         structure="Machined and printed parts; ordered through Taobao and JLC per the project", compute="Not confirmed; 48 V 15 Ah battery",
         price_usd=7000, price_basis="published-total", price_note="About ¥50,000 (≈ $7,000) reported by the project and press; kit pre-orders taken.",
         license_hw="CERN-OHL-W-2.0 (hardware, PCB, BOM, URDF); CC BY-SA 4.0 (docs)", license_sw="GPL-3.0 (firmware, deploy); BSD-3-Clause (training)",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="yes", lic="yes", built="yes"),
         open_notes=dict(cad="Native SolidWorks parts and assemblies plus manufacturing drawings.",
                         elec="Gerbers and schematics; V2 integrates the boards into one core PCB.",
                         built="Built, walking and jumping; ~100 kit pre-orders reported. Builders must match mechanical, PCB and firmware revisions."),
         links=dict(repo="https://github.com/Roboparty/roboto_origin", hardware="https://github.com/Roboparty/rpo_hardware", hub="https://hub.roboparty.com/documents/"),
         sources=["https://github.com/Roboparty/roboto_origin", "https://github.com/Roboparty/rpo_hardware", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://interestingengineering.com/ai-robotics/worlds-first-full-stack-humanoid-robot-open-sourced"],
         summary="A 1.25 m full-stack release: native CAD, drawings, PCB source, firmware, URDF/MJCF, ROS 2 deployment and Isaac Lab training, all licensed.",
         verdict="The strongest large full-stack release found. Needs CNC work and Chinese sourcing; freeze matching revisions before ordering."),

    dict(checked="2026-09-25", id="asimov", name="Asimov v1", org="Menlo Research", year=2026, type="full", status="prototype",
         height_mm=1200, mass_kg=35, dof=25, actuators="Not stated publicly (25 powered joints + 2 passive toes)", family="unknown",
         structure="Machined 7075 aluminium and 316L parts, MJF/SLM prints", compute="Radxa CM5 (motion) + Raspberry Pi 5 (media)",
         price_usd=15000, price_basis="published-total", price_note="DIY kit target ≈ $15,000 with a $499 deposit (summer 2026); an unassembled kit at $20,000 was also reported. BOM by request.",
         license_hw="CERN-OHL-S-2.0", license_sw="GPL-2.0",
         open=dict(cad="partial", bom="partial", docs="partial", elec="yes", fw="partial", sim="yes", policy="partial", lic="yes", built="partial"),
         open_notes=dict(cad="165 per-part STEP files and a whole-robot STEP; no native parametric source.",
                         bom="Marked \"request access\" on the manual.",
                         elec="Native KiCad projects with LCSC part numbers.",
                         fw="Listed as \"coming soon\"; the locomotion policy ships inside it.",
                         built="Physical prototypes exist; kits not yet delivered."),
         links=dict(site="https://menlo.ai/asimov-1", repo="https://github.com/menloresearch/asimov-1", docs="https://docs.menlo.ai/asimov/1", manual="https://manual.asimov.inc/v1/bom"),
         sources=["https://docs.menlo.ai/asimov/1", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://www.opensourceforu.com/2026/05/asimov-v1-open-sources-humanoid-robotics-development/"],
         summary="A 1.2 m, 35 kg humanoid released under CERN-OHL-S with STEP files, KiCad electronics and a MuJoCo model; BOM and firmware still gated.",
         verdict="An open-licensed release in progress: describe it as it exists, not as the finished platform."),

    dict(checked="2026-09-25", id="poppy", name="Poppy Humanoid", org="Inria, Flowers team", year=2014, type="full", status="archive",
         height_mm=830, mass_kg=3.5, dof=25, actuators="25 Dynamixel MX-28 and MX-64 (5-DOF trunk)", family="dynamixel-x",
         structure="3D-printed (SLS or FDM) structure", compute="Odroid XU4 in the head",
         price_usd=8500, price_basis="published-total", price_note="$8,000–9,000 per the project (2015 pricing, about 60 % actuators).",
         license_hw="CC BY-SA 4.0", license_sw="GPL-3.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="no", lic="yes", built="yes"),
         open_notes=dict(cad="SolidWorks source plus STEP, Parasolid and STL.",
                         policy="Walks only with support; not a locomotion platform.",
                         built="Many copies built in labs and schools; last hardware release 2015."),
         links=dict(site="https://www.poppy-project.org/en/robots/poppy-humanoid/", repo="https://github.com/poppy-project/poppy-humanoid"),
         sources=["https://github.com/poppy-project/poppy-humanoid", "https://www.poppy-project.org/en/robots/poppy-humanoid/", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="The clearest early example of a full robot released as editable CAD rather than printable meshes. Dated actuators and no walking.",
         verdict="Meets the definition; conceptually sound, technically old."),

    dict(checked="2026-09-25", id="nico", name="NICO", org="University of Hamburg, WTM", year=2017, type="full", status="prototype",
         height_mm=1010, mass_kg=7, dof=30, actuators="Dynamixel servos; third-party hands", family="dynamixel-x",
         structure="3D-printed", compute="External PC",
         price_usd=None, price_basis="unknown", price_note="No published total.",
         license_hw="CC BY-SA 3.0 (stated by the project; the CAD repository carries no licence file)", license_sw="GPL-3.0",
         open=dict(cad="yes", bom="partial", docs="partial", elec="yes", fw="yes", sim="yes", policy="no", lic="yes", built="yes"),
         open_notes=dict(cad="Native Autodesk Inventor parts and assemblies plus STLs.", policy="Interaction and manipulation platform; it does not walk.", built="Several copies in use at Hamburg and partner labs."),
         links=dict(site="https://www.inf.uni-hamburg.de/en/inst/ab/wtm/research/neurobotics/nico.html", cad="https://github.com/knowledgetechnologyuhh/NICO-cad"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="A child-sized interaction and manipulation humanoid with genuinely open, creator-owned CAD; dependent on proprietary servos and hands.",
         verdict="Open where the creators control the design; reproducibility limited by third-party parts and an older software stack."),

    dict(checked="2026-09-25", id="sapiens", name="AI Sapiens K0 / K1", org="ROBOTIS", year=2026, type="full", status="commercial",
         height_mm=1300, mass_kg=34, dof=23, actuators="Dynamixel Q-series", family="dynamixel-q",
         structure="Not detailed publicly", compute="8-core ARM SoC with NPU",
         price_usd=None, price_basis="unknown", price_note="Not announced; Korean press reports under $10,000.",
         license_hw="Not stated (release announced as open: BOM, CAD, sim assets)", license_sw="Apache-2.0 (ROS 2 packages)",
         open=dict(cad="unknown", bom="unknown", docs="unknown", elec="unknown", fw="yes", sim="yes", policy="partial", lic="unknown", built="yes"),
         open_notes=dict(cad="Announced as open; files not located at the time of writing.", built="Sold and demonstrated by ROBOTIS."),
         links=dict(site="https://ai.robotis.com/ai_sapiens/introduction_ai_sapiens.html", repo="https://github.com/ROBOTIS-GIT/ai_sapiens", docs="https://docs.robotis.com/docs/systems/aisapiens/introduction/"),
         sources=["https://github.com/ROBOTIS-GIT/ai_sapiens", "https://www.humanoidsdaily.com/news/robotis-enters-the-open-source-humanoid-arena-with-ai-sapiens-k0-platform"],
         summary="ROBOTIS's 1.3 m humanoid on its Dynamixel Q actuators, announced as an open platform with ROS 2 packages public first.",
         verdict="Watch: the software is out under Apache-2.0; the hardware release and its licence were not verifiable."),

    dict(checked="2026-09-25", id="kbot", name="K-Bot", org="K-Scale Labs", year=2025, type="full", status="archive",
         height_mm=1400, mass_kg=34, dof=20, actuators="RobStride RS04 ×4, RS03 ×8, RS02 ×6, RS00 ×2 (5 per leg, 5 per arm)", family="robstride-rs",
         structure="Machined and printed", compute="K-OS on an embedded computer",
         price_usd=8999, price_basis="published-total", price_note="Pre-order price for the first 100 units; the company closed in November 2025 and refunded orders.",
         license_hw="CERN-OHL-S", license_sw="GPL-3.0 per README; MIT in the root licence and sub-repositories",
         open=dict(cad="yes", bom="partial", docs="partial", elec="partial", fw="yes", sim="yes", policy="partial", lic="yes", built="partial"),
         open_notes=dict(cad="Onshape and STEP.", bom="Incomplete BOM and electrical path.", built="Two units shipped before closure; no complete build path survives."),
         links=dict(repo="https://github.com/kscalelabs/kbot", site="https://www.kscale.dev/", docs="https://docs.kscale.dev/robots/k-bot/zeroing/"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://www.rs-online.com/designspark/k-scale-labs-launches-k-bot-americas-first-open-source-humanoid-robot", "https://aiwiki.ai/wiki/k_scale_k_bot"],
         summary="A 1.4 m open-licensed humanoid whose company dissolved; the CAD and OS remain as a design archive.",
         verdict="Not reproducible today. The licence preserved the files, not the suppliers or the documentation work."),

    dict(checked="2026-09-25", id="lerobot", name="LeRobot Humanoid (biped)", org="Hugging Face, LeRobot", year=2026, type="biped", status="walking",
         height_mm=None, mass_kg=None, dof=12, actuators="RobStride O0, O2, O3, O5 (CAN-FD)", family="robstride-o",
         structure="3D-printed (75 STL parts) with off-the-shelf bearings and fasteners", compute="Raspberry Pi 5, BNO085 IMU",
         price_usd=2636, price_basis="itemised", price_note="≈ $2,636 as of April 2026 per the hardware repository (motors ≈ $1,880).",
         license_hw="Apache-2.0", license_sw="Apache-2.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="partial", lic="yes", built="partial"),
         open_notes=dict(cad="Public Onshape document organised by subassembly. The model repository's bipedal-platform URDF already carries a folded upper body with RobStride O0 arms, so the upper body exists in CAD; the hardware release covers the biped.", policy="MuJoCo and MJLab training environments; walking shown by the authors.", built="Lower body only; upper body on the roadmap. Third-party builds not confirmed."),
         links=dict(repo="https://github.com/huggingface/lerobot-humanoid-hardware", blog="https://huggingface.co/blog/VirgileBatto/lerobot-humanoid", software="https://github.com/huggingface/lerobot-humanoid"),
         sources=["https://github.com/huggingface/lerobot-humanoid-hardware", "https://huggingface.co/blog/VirgileBatto/lerobot-humanoid"],
         summary="A printed 12-DOF biped on RobStride O-series actuators with an itemised $2,600 BOM, Onshape source and Apache-2.0 terms.",
         verdict="Incomplete as a humanoid, excellent as a biped: the best-documented low-cost legs in this list."),

    dict(checked="2026-09-25", id="agiloped", name="AGILOped", org="University of Bonn, NimbRo", year=2025, type="full", status="prototype",
         height_mm=1100, mass_kg=14.5, dof=12, actuators="10 actuators driving 12 joints (models not confirmed)", family="unknown",
         structure="Not detailed", compute="Not detailed",
         price_usd=None, price_basis="unknown", price_note="No procurement BOM.",
         license_hw="MIT", license_sw="BSD-3-Clause",
         open=dict(cad="partial", bom="no", docs="no", elec="unknown", fw="yes", sim="yes", policy="yes", lic="yes", built="partial"),
         open_notes=dict(cad="STEP files, URDF and MuJoCo assets.", policy="Walking, jumping, fall mitigation and recovery demonstrated.", built="Authors only."),
         links=dict(site="https://nimbro.net/Humanoid/AGILOped/", repo="https://github.com/gficht/AGILOped_model", paper="https://arxiv.org/abs/2509.09364"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="A 1.1 m, 14.5 kg walker with strong physical demonstrations and MIT-licensed STEP, but no BOM or assembly manual.",
         verdict="Incomplete: a model release, not a build release."),

    dict(checked="2026-09-25", id="nimbro", name="NimbRo-OP2X", org="University of Bonn, NimbRo", year=2018, type="full", status="walking",
         height_mm=1350, mass_kg=19, dof=18, actuators="34 × Dynamixel XH540-W270-R on 18 joints", family="dynamixel-x",
         structure="SLS nylon-12 (PA12)", compute="Intel i7-8700T + GTX 1050 Ti",
         price_usd=None, price_basis="unknown", price_note="\"Similar price range to Baxter\" per the paper; no figure.",
         license_hw="CC BY-NC-SA 3.0 (stated in the hardware repository; no licence file)", license_sw="BSD-3-Clause",
         open=dict(cad="yes", bom="yes", docs="partial", elec="yes", fw="yes", sim="yes", policy="yes", lic="no", built="yes"),
         open_notes=dict(lic="Non-commercial clause fails the open-hardware definition.", policy="RoboCup AdultSize champion; walking and perception stack released."),
         links=dict(repo="https://github.com/NimbRo/nimbro-op2", software="https://github.com/AIS-Bonn/humanoid_op_ros", paper="https://arxiv.org/abs/2010.09308"),
         sources=["https://arxiv.org/abs/2010.09308", "https://github.com/stephane-caron/awesome-open-source-robots"],
         summary="An adult-sized SLS-printed soccer humanoid on Dynamixel XH540s with a released CAD and BOM.",
         verdict="Reproducible and proven, but non-commercial."),

    dict(checked="2026-09-25", id="igus", name="igus Humanoid Open Platform", org="University of Bonn, NimbRo with igus", year=2015, type="full", status="archive",
         height_mm=900, mass_kg=None, dof=None, actuators="Dynamixel MX-series", family="dynamixel-x",
         structure="SLS-printed", compute="Intel NUC",
         price_usd=None, price_basis="unknown", price_note="Printed-parts set priced on request from igus.",
         license_hw="Not stated on the project page", license_sw="BSD-3-Clause",
         open=dict(cad="yes", bom="unknown", docs="partial", elec="yes", fw="yes", sim="partial", policy="yes", lic="unknown", built="yes"),
         open_notes=dict(cad="CAD and initial software on GitHub (igusGmbH/HumanoidOpenPlatform).", built="RoboCup TeenSize winner 2016; superseded by NimbRo-OP2X."),
         links=dict(site="http://nimbro.net/OP/", repo="https://github.com/igusGmbH/HumanoidOpenPlatform"),
         sources=["http://nimbro.net/OP/"],
         summary="The 2015 child-sized printed platform that led to NimbRo-OP2X.",
         verdict="Historical; licence not stated."),

    dict(checked="2026-09-25", id="toddlerbot", name="ToddlerBot 2.0", org="Stanford University", year=2025, type="full", status="walking",
         height_mm=560, mass_kg=3.4, dof=30, actuators="Dynamixel 2XC430, 2XL430, XC330, XC430, XM430", family="dynamixel-x",
         structure="FDM-printed", compute="NVIDIA Jetson Orin NX",
         price_usd=6000, price_basis="published-total", price_note="≈ $6,000 BOM per the paper, 90 % in the Jetson and the Dynamixels; a third-party assembled kit is sold at $4,299.",
         license_hw="CC BY-NC-SA 4.0 (Onshape and STL)", license_sw="MIT",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="yes", lic="no", built="yes"),
         open_notes=dict(docs="MakerWorld 3MF plates with materials and times; JLCPCB ordering walkthrough.", lic="Non-commercial terms; a company gets no right to build on the hardware.", built="Independent reproductions reported; assembled units sold by a third party."),
         links=dict(site="https://toddlerbot.github.io/", repo="https://github.com/hshi74/toddlerbot", paper="https://arxiv.org/abs/2502.00893"),
         sources=["https://arxiv.org/abs/2502.00893", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "Duke_Humanoid_V2_OpenSource/reference/bom/toddlerbot_BOM_release.csv"],
         summary="A 56 cm, 30-DOF, entirely printed humanoid for loco-manipulation learning; the most complete build documentation in the list.",
         verdict="Excellent source-available research platform; fails the open-hardware definition on the non-commercial clause."),

    dict(checked="2026-09-25", id="microban", name="Microban", org="Rhoban, Bordeaux", year=2025, type="mini", status="walking",
         height_mm=300, mass_kg=None, dof=19, actuators="Small serial bus servos (see BOM)", family="unknown",
         structure="FDM-printed", compute="Onboard SBC",
         price_usd=567, price_basis="itemised", price_note="≈ $567 in parts before tools, per the project BOM.",
         license_hw="CC BY-NC-SA 4.0", license_sw="GPL-3.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="partial", lic="no", built="yes"),
         open_notes=dict(lic="Non-commercial."),
         links=dict(repo="https://github.com/Rhoban/microban", bom="https://github.com/Rhoban/microban/blob/main/docs/bom.md"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://github.com/stephane-caron/awesome-open-source-robots"],
         summary="A 30 cm, 19-DOF desktop humanoid with a detailed BOM and an RL environment.",
         verdict="Research-only terms, like ToddlerBot."),

    dict(checked="2026-09-25", id="zeroth", name="Zeroth-01 / Z-Bot", org="K-Scale Labs (community)", year=2024, type="mini", status="archive",
         height_mm=400, mass_kg=None, dof=16, actuators="16 × Feetech STS3215 / STS3250", family="feetech-sts",
         structure="FDM-printed", compute="Milk-V Duo S (RISC-V) in the original; community builds use a Raspberry Pi 4",
         price_usd=350, price_basis="published-total", price_note="\"BoM starts at $350\" per the repository.",
         license_hw="MIT", license_sw="MIT",
         open=dict(cad="yes", bom="yes", docs="partial", elec="yes", fw="yes", sim="yes", policy="partial", lic="yes", built="yes"),
         open_notes=dict(built="Built at hackathons; replaced by Z-Bot, then orphaned when K-Scale closed."),
         links=dict(repo="https://github.com/zeroth-robotics/zeroth-bot"),
         sources=["https://github.com/zeroth-robotics/zeroth-bot", "https://circuitdigest.com/news/zeroth-bot-an-opensource-risc-v-powered-humanoid-robot", "https://github.com/Justin-Riekehof/zeroth-01-build"],
         summary="A $350, 16-DOF printed mini humanoid with vision and speech on a RISC-V board.",
         verdict="Cheap, MIT-licensed, unmaintained."),

    dict(checked="2026-09-25", id="duck", name="Open Duck Mini v2", org="Antoine Pirrone (community)", year=2025, type="biped", status="walking",
         height_mm=420, mass_kg=None, dof=14, actuators="14 × Feetech STS3215 (5 per leg, 4 in the neck and head)", family="feetech-sts",
         structure="FDM-printed", compute="Raspberry Pi Zero 2 W",
         price_usd=400, price_basis="published-total", price_note="\"Under $400\" per the project; itemised Google Sheet BOM.",
         license_hw="Apache-2.0", license_sw="Apache-2.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="yes", lic="yes", built="yes"),
         open_notes=dict(policy="Trained ONNX walking policies run on the Pi; MuJoCo Playground environment.", built="Widely reproduced; third-party kits exist."),
         links=dict(repo="https://github.com/apirrone/Open_Duck_Mini", docs="https://tnkr.ai/explore/docs/open-duck-mini/open-duck-mini-v2"),
         sources=["https://github.com/apirrone/Open_Duck_Mini/blob/v2/README.md", "https://github.com/stephane-caron/awesome-open-source-robots"],
         summary="A 42 cm walking droid built by hundreds of people for under $400, with the whole RL pipeline public.",
         verdict="Meets the definition and is reproduced at scale; a biped, not a humanoid."),

    dict(checked="2026-09-25", id="bolt", name="Bolt", org="Open Dynamic Robot Initiative (MPI-IS, NYU, LAAS)", year=2021, type="biped", status="walking",
         height_mm=None, mass_kg=None, dof=6, actuators="ODRI brushless modules (T-motor + 9:1 belt stage + open driver board)", family="odri",
         structure="Printed structure with carbon tubes", compute="Off-board PC via ODRI master board",
         price_usd=6400, price_basis="third-party", price_note="≈ $6,400 to build in the US, estimated by a third party; ODRI publishes the BOM.",
         license_hw="BSD-3-Clause", license_sw="BSD-3-Clause",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="yes", policy="partial", lic="yes", built="yes"),
         open_notes=dict(elec="Driver and master boards are open designs.", built="Reproduced in several labs."),
         links=dict(site="https://open-dynamic-robot-initiative.github.io/", repo="https://github.com/open-dynamic-robot-initiative/bolt"),
         sources=["https://open-dynamic-robot-initiative.github.io/", "https://github.com/stephane-caron/awesome-open-source-robots", "https://easybuildtech.com/open-dynamic-robot-initiative-open-source-biped/"],
         summary="A 6-DOF research biped built from ODRI's open actuator module and electronics.",
         verdict="Fully open and reproduced; a lab platform rather than a humanoid."),

    dict(checked="2026-09-25", id="mevita", name="MEVITA", org="JSK, University of Tokyo", year=2025, type="biped", status="walking",
         height_mm=None, mass_kg=None, dof=None, actuators="CubeMars AK70-10 and AK10-9 V2 (MIT mode)", family="cubemars-ak",
         structure="18 sheet-metal welded parts", compute="Onboard PC",
         price_usd=None, price_basis="unknown", price_note="No published total.",
         license_hw="MIT", license_sw="MIT",
         open=dict(cad="yes", bom="partial", docs="partial", elec="yes", fw="yes", sim="yes", policy="yes", lic="yes", built="partial"),
         open_notes=dict(cad="CAD on Google Drive.", policy="legged_gym training, MuJoCo verification, deployed."),
         links=dict(site="https://haraduka.github.io/mevita-hardware/", repo="https://github.com/haraduka/mevita"),
         sources=["https://github.com/haraduka/mevita", "https://haraduka.github.io/mevita-hardware/"],
         summary="A minimal sheet-metal biped on CubeMars actuators with the full sim-to-real pipeline released.",
         verdict="Open and clever; no BOM total."),

    dict(checked="2026-09-25", id="hopejr", name="HopeJR", org="The Robot Studio with Hugging Face", year=2025, type="upper", status="prototype",
         height_mm=None, mass_kg=None, dof=66, actuators="Feetech STS-series bus servos (arms and hands)", family="feetech-sts",
         structure="FDM-printed", compute="LeRobot host PC",
         price_usd=3000, price_basis="published-total", price_note="≈ $3,000 per Hugging Face's announcement; no whole-robot BOM.",
         license_hw="Apache-2.0 on the Humanoid subtree; root and newer arm subtree unlicensed", license_sw="Apache-2.0 (LeRobot)",
         open=dict(cad="partial", bom="partial", docs="partial", elec="yes", fw="partial", sim="partial", policy="no", lic="partial", built="partial"),
         open_notes=dict(built="Arms and hands demonstrated with glove teleoperation; no walking controller."),
         links=dict(repo="https://github.com/TheRobotStudio/HOPEJr", docs="https://huggingface.co/docs/lerobot/main/en/hope_jr"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://github.com/TheRobotStudio/HOPEJr"],
         summary="Printed arms and dexterous hands on bus servos, teleoperated with gloves; a full-body concept with the upper body real.",
         verdict="Incomplete and inconsistently licensed across the repository."),

    dict(checked="2026-09-25", id="amazing-hand", name="Amazing Hand", org="Pollen Robotics / Hugging Face", year=2025, type="hand", status="prototype",
         height_mm=None, mass_kg=0.4, dof=8, actuators="8 small bus servos per hand", family="feetech-sts",
         structure="Fully 3D-printed, flexible fingers", compute="Any host via servo bus",
         price_usd=220, price_basis="itemised", price_note="Under €200 per hand in off-the-shelf parts per Pollen's BOM.",
         license_hw="Apache-2.0", license_sw="Apache-2.0",
         open=dict(cad="yes", bom="yes", docs="yes", elec="yes", fw="yes", sim="partial", policy="partial", lic="yes", built="yes"),
         open_notes=dict(built="Reproduced widely since release."),
         links=dict(blog="https://huggingface.co/blog/pollen-robotics/amazing-hand", repo="https://github.com/pollen-robotics/AmazingHand"),
         sources=["https://huggingface.co/blog/pollen-robotics/amazing-hand"],
         summary="An 8-DOF printed hand for under €200 with BOM, print guide and assembly guide.",
         verdict="Meets the definition; the cheapest open hand worth bolting on."),

    dict(checked="2026-09-25", id="inmoov", name="InMoov", org="Gaël Langevin (community)", year=2012, type="upper", status="walking",
         height_mm=None, mass_kg=None, dof=None, actuators="28 hobby PWM servos", family="hobby-pwm",
         structure="FDM-printed life-size shell", compute="2 × Arduino Mega with Nervo boards",
         price_usd=1200, price_basis="third-party", price_note="$1,000–1,500 per builders' reports; parts list on the project site.",
         license_hw="CC BY-NC", license_sw="MyRobotLab (Apache-2.0)",
         open=dict(cad="partial", bom="yes", docs="yes", elec="yes", fw="yes", sim="partial", policy="no", lic="no", built="yes"),
         open_notes=dict(cad="STL only.", lic="Non-commercial.", built="Thousands built; legs are not motorised."),
         links=dict(site="https://inmoov.fr/"),
         sources=["https://inmoov.fr/project/", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="The original life-size printable maker humanoid: upper body, hobby servos, huge community.",
         verdict="A maker platform under non-commercial terms, not a walking robot."),

    dict(checked="2026-09-25", id="op3", name="ROBOTIS OP3", org="ROBOTIS", year=2017, type="full", status="commercial",
         height_mm=510, mass_kg=3.5, dof=20, actuators="Dynamixel XM430-W350", family="dynamixel-x",
         structure="Aluminium frames and plastic covers", compute="Intel NUC i3",
         price_usd=11969, price_basis="published-total", price_note="List price at ROBOTIS US.",
         license_hw="STP parts and schematics published; no unified hardware licence (Dynamixel firmware closed)", license_sw="Apache-2.0",
         open=dict(cad="partial", bom="partial", docs="yes", elec="partial", fw="partial", sim="yes", policy="yes", lic="partial", built="yes"),
         open_notes=dict(cad="STP exports of every frame.", elec="OpenCR board is open (BOM, Gerbers, firmware); the actuators are not."),
         links=dict(docs="https://emanual.robotis.com/docs/en/platform/op3/introduction/", shop="https://www.robotis.us/robotis-op3-us/"),
         sources=["https://emanual.robotis.com/docs/en/platform/op3/hardware/", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="A supported commercial kid-size humanoid with unusually complete public drawings and ROS software.",
         verdict="Inspectable and modifiable, not open all the way down."),

    dict(checked="2026-09-25", id="icub", name="iCub", org="Istituto Italiano di Tecnologia", year=2009, type="full", status="commercial",
         height_mm=1040, mass_kg=22, dof=53, actuators="Custom brushless and brushed motors with in-house boards", family="unknown",
         structure="Machined aluminium", compute="Onboard PC104 + external cluster",
         price_usd=None, price_basis="unknown", price_note="Supplied by IIT; about €250,000 per unit is the commonly cited figure (Wikipedia), depending on version.",
         license_hw="CERN-OHL-W-2.0 for the public subset; CC BY-SA models; historically GPL/LGPL", license_sw="GPL (core), BSD elsewhere",
         open=dict(cad="partial", bom="no", docs="partial", elec="partial", fw="yes", sim="yes", policy="partial", lic="partial", built="yes"),
         open_notes=dict(cad="Public repositories mirror selected material from private engineering repositories.", built="Dozens of units in labs worldwide."),
         links=dict(site="https://icub.iit.it/", cad="https://github.com/icub-tech-iit/cad-mechanics-public", elec="https://github.com/icub-tech-iit/electronics-boards-public"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://en.wikipedia.org/wiki/ICub"],
         summary="The long-running open research humanoid: open software and models, selected open hardware, commercial supply.",
         verdict="Calling it closed would be wrong; calling every part open hardware would also be wrong."),

    dict(checked="2026-09-25", id="bruce", name="BRUCE", org="Westwood Robotics with RoMeLa", year=2022, type="full", status="commercial",
         height_mm=None, mass_kg=None, dof=16, actuators="Westwood BEAR actuators", family="bear",
         structure="Machined", compute="Onboard SBC",
         price_usd=8890, price_basis="published-total", price_note="Limited-time price; list price $15,290.",
         license_hw="GPL-3.0 with a commercial licence option", license_sw="GPL-3.0",
         open=dict(cad="partial", bom="partial", docs="partial", elec="no", fw="yes", sim="yes", policy="yes", lic="partial", built="yes"),
         open_notes=dict(cad="Wiki and CAD behind developer access at the time of writing.", elec="BEAR actuators are proprietary."),
         links=dict(site="https://www.westwoodrobotics.io/bruce/", wiki="https://wiki.bruce-op.com/"),
         sources=["https://www.westwoodrobotics.io/bruce/"],
         summary="A kid-size compliant biped sold as an open platform on proprietary BEAR actuators.",
         verdict="Open-source software, gated hardware."),

    dict(checked="2026-09-25", id="agibot-x1", name="AgiBot X1 (Lingxi X1)", org="AgiBot", year=2024, type="full", status="commercial",
         height_mm=1300, mass_kg=33, dof=34, actuators="AgiBot PowerFlow actuators", family="unknown",
         structure="Machined and moulded", compute="Onboard PC with AimRT middleware",
         price_usd=None, price_basis="unknown", price_note="Kits listed by resellers; no project BOM total.",
         license_hw="None stated", license_sw="Mulan PSL v2",
         open=dict(cad="yes", bom="yes", docs="yes", elec="partial", fw="yes", sim="yes", policy="yes", lic="no", built="yes"),
         open_notes=dict(cad="Native SolidWorks archives, whole-machine STEP, drawings and assembly SOP.", lic="The hardware repository has no licence granting reuse."),
         links=dict(repo="https://github.com/AgibotTech/agibot_x1_hardware", train="https://github.com/AgibotTech/agibot_x1_train"),
         sources=["https://github.com/AgibotTech/agibot_x1_hardware", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots", "https://www.agibot.com/products/X1"],
         summary="A 1.3 m modular humanoid with native CAD, BOM and SOP published, but no hardware licence.",
         verdict="Files without permission: fails the definition on licensing alone."),

    dict(checked="2026-09-25", id="fourier-n1", name="Fourier N1", org="Fourier", year=2025, type="full", status="announced",
         height_mm=1300, mass_kg=38, dof=23, actuators="Fourier FSA 2.0", family="unknown",
         structure="Machined", compute="Onboard PC",
         price_usd=None, price_basis="unknown", price_note="Not published.",
         license_hw="None stated", license_sw="MIT (SDK documentation repository)",
         open=dict(cad="no", bom="no", docs="no", elec="no", fw="partial", sim="yes", policy="partial", lic="no", built="yes"),
         open_notes=dict(cad="Announced as fully open with BOM, STEP and SOP; the public repository is SDK documentation only."),
         links=dict(repo="https://github.com/FFTAI/fourier-grx-N1"),
         sources=["https://github.com/FFTAI/fourier-grx-N1", "https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="Announced as the first open-source humanoid; the hardware package had not appeared where the announcement pointed.",
         verdict="Promised, not delivered."),

    dict(checked="2026-09-25", id="tienkung", name="Tien Kung (Tiangong)", org="X-Humanoid, Beijing Humanoid Robot Innovation Center", year=2024, type="full", status="announced",
         height_mm=None, mass_kg=None, dof=None, actuators="Not stated", family="unknown",
         structure="Machined", compute="Onboard PC",
         price_usd=None, price_basis="unknown", price_note="Not published.",
         license_hw="None stated", license_sw="Apache-2.0 (training toolchain), MIT (xMimic)",
         open=dict(cad="no", bom="no", docs="no", elec="no", fw="yes", sim="yes", policy="yes", lic="no", built="yes"),
         open_notes=dict(cad="URDF and STL released; hardware design release announced for Tien Kung 3.0, not found."),
         links=dict(org="https://github.com/Open-X-Humanoid", urdf="https://github.com/Open-X-Humanoid/TienKung_URDF"),
         sources=["https://github.com/Open-X-Humanoid"],
         summary="A full-size running humanoid with open training code and URDF; hardware openness announced repeatedly.",
         verdict="Open software around closed hardware until the CAD appears."),

    dict(checked="2026-09-25", id="openloong", name="OpenLoong", org="Shanghai Humanoid Robot Innovation Center", year=2024, type="full", status="commercial",
         height_mm=None, mass_kg=None, dof=None, actuators="Not stated", family="unknown",
         structure="Machined", compute="Onboard PC",
         price_usd=None, price_basis="unknown", price_note="Not published.",
         license_hw="Solderpad 2.1", license_sw="Not stated",
         open=dict(cad="partial", bom="no", docs="partial", elec="no", fw="partial", sim="yes", policy="partial", lic="yes", built="yes"),
         open_notes=dict(cad="STEP exports and PDFs; no native CAD, ECAD or full arm and hand source."),
         links=dict(repo="https://github.com/loongOpen/Openloong-hardware"),
         sources=["https://www.humanoidsdata.com/articles/open-source-humanoid-robots"],
         summary="A licensed but thin hardware tree: STEP and PDFs without BOM.",
         verdict="Licence ahead of reproducibility."),
]

# Open files around closed hardware: listed so the checklist has a comparison row, not as options.
CLOSED = [
    dict(name="Unitree G1", price="$16,000–25,000", released="URDF/MJCF, SDKs, datasets", why="No mechanical source, electronics or BOM; proprietary hardware.", url="https://github.com/unitreerobotics/unitree_ros/tree/master/robots/g1_description"),
    dict(name="Booster T1", price="on request", released="Models and a training-to-deployment stack", why="Proprietary hardware.", url="https://github.com/BoosterRobotics/booster_gym"),
    dict(name="Fourier GR-1 / GR-2", price="on request", released="Models and developer software", why="Proprietary hardware.", url="https://github.com/FFTAI/Wiki-GRx-Models"),
    dict(name="Reachy 2", price="≈ $70,000", released="ROS 2 stack and SDK", why="CAD page marked in progress; no reproduction permission.", url="https://docs.pollen-robotics.com/hardware-guide/makers/cad-files/"),
]

# --- modules for the builder (robots whose subsystems are separable and priced) ---------
# FOH and Duke V2 modules are computed by build_catalog.py. These are static.
# price_basis: itemised | estimate | published-total | third-party | unknown
# top / bottom / side describe the mechanical interface at the module boundary.

MODULES = [
    dict(id="lerobot-lower", robot="lerobot", slot="lower", name="LeRobot Humanoid biped", dof=12, mass_kg=None, price_usd=2636, price_basis="itemised",
         scale_mm=800, payload_kg=None, family="robstride-o",
         top=dict(joint="pelvis top plate", mount="printed pelvis plate (no waist actuator)"),
         bom=[dict(item="RobStride O-series actuators (O0, O2, O3, O5), 12", qty=1, unit=1880, vendor="RobStride", url="https://www.robstride.com/"),
              dict(item="Printed parts, bearings, fasteners, Raspberry Pi 5, IMU, harness", qty=1, unit=756, vendor="various (see repository BOM)", url="https://github.com/huggingface/lerobot-humanoid-hardware")],
         notes="Two-line summary of the repository's April 2026 BOM; the itemised sheet is in the hardware repository."),
    dict(id="duck-lower", robot="duck", slot="lower", name="Open Duck Mini v2 legs (whole robot)", dof=10, mass_kg=1.6, price_basis="published-total", price_usd=400,
         scale_mm=420, payload_kg=0.5, family="feetech-sts",
         top=dict(joint="body", mount="printed body shell"),
         bom=[dict(item="Feetech STS bus servos, printed parts, Raspberry Pi Zero 2 W, battery", qty=1, unit=400, vendor="various (project BOM sheet)", url="https://github.com/apirrone/Open_Duck_Mini")],
         notes="A 42 cm droid; listed to show what the checks say when scales do not match. DOF and mass are approximate."),
    dict(id="bolt-lower", robot="bolt", slot="lower", name="ODRI Bolt biped", dof=6, mass_kg=None, price_usd=6400, price_basis="third-party",
         scale_mm=500, payload_kg=None, family="odri",
         top=dict(joint="hip frame", mount="ODRI hip frame"),
         bom=[dict(item="ODRI actuator modules, master board, printed structure (see ODRI BOM)", qty=1, unit=6400, vendor="ODRI suppliers", url="https://github.com/open-dynamic-robot-initiative/bolt")],
         notes="Third-party US build estimate."),
    dict(id="mevita-lower", robot="mevita", slot="lower", name="MEVITA biped", dof=None, mass_kg=None, price_usd=None, price_basis="unknown",
         scale_mm=None, payload_kg=None, family="cubemars-ak",
         top=dict(joint="pelvis", mount="sheet-metal pelvis"),
         bom=[dict(item="CubeMars AK70-10 and AK10-9 V2 actuators, welded sheet-metal parts", qty=1, unit=None, vendor="CubeMars; sheet-metal shop", url="https://github.com/haraduka/mevita")],
         notes="No published total."),
    dict(id="bhl-lower", robot="bhl", slot="lower", name="Berkeley Humanoid Lite legs", dof=12, mass_kg=None, price_usd=2700, price_basis="estimate",
         scale_mm=800, payload_kg=None, family="bhl",
         top=dict(joint="pelvis", mount="printed pelvis"),
         bom=[dict(item="12 printed cycloidal actuators (motor, controller board, bearings, prints)", qty=12, unit=None, vendor="see BHL BOM sheet", url="https://berkeley-humanoid-lite.gitbook.io/docs/getting-started-with-hardware/materials-and-parts-bom"),
              dict(item="Printed leg structure, feet, fasteners", qty=1, unit=None, vendor="see BHL BOM sheet", url="https://berkeley-humanoid-lite.gitbook.io/docs/getting-started-with-hardware/materials-and-parts-bom")],
         notes="Estimate: 12 of 22 joints of a sub-$5,000 robot, pro rata. The project publishes the itemised sheet."),
    dict(id="bhl-torso", robot="bhl", slot="torso", name="Berkeley Humanoid Lite torso", dof=0, mass_kg=None, price_usd=600, price_basis="estimate",
         scale_mm=800, family="none", bottom=dict(joint="pelvis", mount="printed pelvis"), side=dict(joint="shoulder", mount="printed actuator cup"),
         bom=[dict(item="Printed torso, computer, battery, IMU, harness", qty=1, unit=None, vendor="see BHL BOM sheet", url="https://berkeley-humanoid-lite.gitbook.io/docs/getting-started-with-hardware/materials-and-parts-bom")],
         notes="Estimate."),
    dict(id="bhl-arms", robot="bhl", slot="arms", name="Berkeley Humanoid Lite arms", dof=10, mass_kg=None, price_usd=1700, price_basis="estimate",
         scale_mm=800, family="bhl", top=dict(joint="shoulder", mount="printed actuator cup"), bottom=dict(joint="wrist", mount="printed wrist plate"),
         bom=[dict(item="10 printed cycloidal actuators and printed arm structure", qty=10, unit=None, vendor="see BHL BOM sheet", url="https://berkeley-humanoid-lite.gitbook.io/docs/getting-started-with-hardware/materials-and-parts-bom")],
         notes="Estimate: 10 of 22 joints, pro rata."),
    dict(id="amazing-hands", robot="amazing-hand", slot="hands", name="Amazing Hand, pair", dof=16, mass_kg=0.8, price_usd=440, price_basis="itemised",
         scale_mm=None, family="feetech-sts", top=dict(joint="wrist", mount="flat wrist flange, printed"),
         bom=[dict(item="Amazing Hand parts (8 bus servos, prints, fasteners), per hand", qty=2, unit=220, vendor="see Pollen BOM", url="https://github.com/pollen-robotics/AmazingHand")],
         notes="Under €200 per hand per Pollen; converted at €1 ≈ $1.10."),
    dict(id="hopejr-arms", robot="hopejr", slot="arms", name="HopeJR arms, pair", dof=14, mass_kg=None, price_usd=None, price_basis="unknown",
         scale_mm=1700, family="feetech-sts", top=dict(joint="shoulder", mount="printed shoulder mount"), bottom=dict(joint="wrist", mount="printed wrist"),
         bom=[dict(item="Feetech bus servos and printed arm parts (see repository)", qty=1, unit=None, vendor="see HopeJR repository", url="https://github.com/TheRobotStudio/HOPEJr")],
         notes="No whole-arm BOM total published."),
    dict(id="hopejr-hands", robot="hopejr", slot="hands", name="HopeJR dexterous hands, pair", dof=32, mass_kg=None, price_usd=None, price_basis="unknown",
         scale_mm=None, family="feetech-sts", top=dict(joint="wrist", mount="printed wrist"),
         bom=[dict(item="Feetech bus servos and printed hand parts (see repository)", qty=1, unit=None, vendor="see HopeJR repository", url="https://github.com/TheRobotStudio/HOPEJr")],
         notes="No BOM total published."),
]

# Combinations someone has actually built. Same-robot combinations of built robots are
# implied; add cross-project builds here with evidence.
VERIFIED_COMBOS = [
    # dict(modules=["duke2-lower", "foh-torso"], status="verified", by="", evidence="", url="")
]
